version: "2"

services:
    spark-master:
        image: wlezzar/spark:1.6.2-hadoop-2.6
        ports:
            - "18080:8080"
        environment: 
            JMX_PORT: "9999"
        command: spark-class org.apache.spark.deploy.master.Master -h spark-master
    spark-worker:
        image: wlezzar/spark:1.6.2-hadoop-2.6
        command: spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
        depends_on: 
            - spark-master