version: "2"

services:
  zookeeper:
    image: wlezzar/zookeeper-exhibitor:confluent-3.1.1
    ports:
      - "8080:8080"
    network_mode: host
  kafka:
    image: wlezzar/kafka:confluent-3.1.1
    depends_on:
      - zookeeper
    environment:
      JMX_PORT: "9999"
    network_mode: host
  schema-registry:
    image: wlezzar/schema-registry:confluent-3.1.1
    depends_on:
      - zookeeper
      - kafka
    environment:
      WAIT_FOR_TCP: "localhost:9092"
    network_mode: host
  kafka-rest:
    image: wlezzar/kafka-rest:confluent-3.1.1
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    network_mode: host
    environment:
      WAIT_FOR_TCP: "localhost:9092,localhost:8081"
  burrow:
    image: wlezzar/burrow:1.0
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    network_mode: host
    environment:
      PAUSE_BEFORE_START: 60
      BURROW_GROUP_BLACKLIST: '^(python-kafka-consumer-).*$$'
      BURROW_LAGCHECK_INTERVAL: 2
