version: "2"

services:
  zookeeper:
    image: wlezzar/zookeeper:confluent-2.0.1
  kafka:
    image: wlezzar/kafka:confluent-2.0.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_CONF_zookeeper_connect: "zookeeper:2181"
  schema-registry:
    image: wlezzar/schema-registry:confluent-2.0.1
    depends_on:
      - zookeeper
      - kafka
    environment:
      SR_CONF_kafkastore_connection_url: "zookeeper:2181"
      WAIT_FOR_TCP: "kafka:9092"
  kafka-rest:
    image: wlezzar/kafka-rest:confluent-2.0.1
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    environment:
      KAFKA_REST_CONF_zookeeper_connect: "zookeeper:2181"
      WAIT_FOR_TCP: "kafka:9092,schema-registry:8081"
