FROM openjdk:8

ENV DOCKERIZE_VERSION=v0.2.1 GOSU_VERSION=1.9

# Install dockerize
RUN curl -sL --retry 3 \
      https://github.com/wlezzar/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-$DOCKERIZE_VERSION.tar.gz \
      | tar -zx -C /usr/local/bin

# Install Gosu
RUN set -x \
    && dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')" \
    && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch" \
    && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc" \
    && export GNUPGHOME="$(mktemp -d)" \
    && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
    && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
    && rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc \
    && chmod +x /usr/local/bin/gosu \
    && gosu nobody true

COPY utils /utils