version: "2"

services:
  zookeeper:
    image: wlezzar/zookeeper-exhibitor:confluent-2.0.1
    ports:
      - "8080:8080"
  kafka:
    image: wlezzar/kafka:confluent-2.0.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_CONF_zookeeper_connect: "zookeeper:2181"
      ADVERTISE_INTERFACE: "eth0"
